run:
  # Timeout for analysis
  timeout: 5m
  
  # Don't re-download modules
  modules-download-mode: readonly
  
  # Use all available CPU cores
  concurrency: 0
  
  # Allow multiple parallel golangci-lint runs
  allow-parallel-runners: true

linters:
  # Disable all linters by default
  disable-all: true
  
  # Enable only essential fast linters
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused code
    - gofmt         # Check formatting
    - goimports     # Check imports
    - misspell      # Check for misspelled words
    - revive        # Fast, configurable, extensible linter
  
  # Run only fast linters from enabled linters set
  fast: true

linters-settings:
  errcheck:
    # Don't check for errors from these functions
    check-type-assertions: false
    check-blank: false
    
  govet:
    # Enable specific checks (shadow disabled for performance)
    enable:
      - atomic
      - bools
      - buildtag
      - nilfunc
      - printf
    disable:
      - shadow
      - fieldalignment
    
  staticcheck:
    # Use all checks
    checks: ["all"]
    
  unused:
    # Treat code as a program (not a library)
    check-exported: false
    
  revive:
    # Minimal revive rules for speed
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text
  max-same-issues: 0
  
  # Exclude known issues
  exclude-use-default: true
  
  # Exclude vendor and .git from all checks
  exclude-dirs:
    - vendor
    - .git

output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate
  formats: colored-line-number
  
  # Print lines of code with issue
  print-issued-lines: true
  
  # Print linter name in the end of issue text
  print-linter-name: true
  
  # Sort results by: filepath, line, and column
  sort-results: true

